logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://docker-container-name:5432/habr
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

app:
  picture:
    storage:
      path: /storage